# Site Settings
title:               ACT1ON
tagline:             Helping you take one political action a day to change the world
description:
baseurl:            #"/inde"
url:                #"https://lenpaul.github.io"
github:
  url:               #"https://lenpaul.github.io/Lagrange"
author:
  name:              "Justin Aronstein"
  email:             "contact@act1on.io+"
  twitter:           "act1on"
#  instagram:         "paululele"
#  github:            "lenpaul"
  facebook:          "act1on"
  linkedin:          "jaronstein"
paginate:            5
paginate-path:       Actions/page:num


# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
